### ISSUE TITLE
Build artifact missing on Jitpack.io

### ISSUE THREAD

**Issue by marlonbosse** [phrase/phraseapp-android#11]
It seems something went wrong in the build-pipeline, all logs on jitpack.io stating an error:
https://jitpack.io/#phrase/phraseapp-android

And no artifacts are accessible.

**Comment by theSoenke** [comment]
Hi @marlonbosse, the actual package is `phrase/android-sdk`. Could you try using `com.github.phrase:android-sdk:1.2.0`? Let me know in case you are still experiencing any issues

**Comment by marlonbosse** [comment]
Thanks for the quick reply @theSoenke unfortunately this dependency isn't resolvable for me. Do I need special access rights? It used to work for `1.1.3` just fine.

**Comment by theSoenke** [comment]
I just have been running into the same issue. All build artifacts should be public and there has been no change from our side. I will check with Jitpack what might have happened here

**Comment by theSoenke** [comment]
This issue might be related: https://github.com/jitpack/jitpack.io/issues/4039

**Comment by marlonbosse** [comment]
It seems that this might take a while – are you considering to host it somewhere else?

**Comment by theSoenke** [comment]
We are currently in the process of migrating to a different provider. We will try to resolve this as soon as possible and provide an update as soon as it is available

**Comment by rodrigoarias** [comment]
Having the same issue here, we are getting this:

```
 Could not resolve com.github.phrase:android-sdk:1.1.5.
     Required by:
         project :app
      > Could not resolve com.github.phrase:android-sdk:1.1.5.
         > Could not get resource 'https://jitpack.io/com/github/phrase/android-sdk/1.1.5/android-sdk-1.1.5.pom'.
            > Could not GET 'https://jitpack.io/com/github/phrase/android-sdk/1.1.5/android-sdk-1.1.5.pom'. Received status code 401 from server: Unauthorized
```

**Comment by theSoenke** [comment]
If this helps here is a direct link to the latest aar file: https://dl.bintray.com/phrase/Phrase/com/phrase/android/sdk/1.2.0/sdk-1.2.0.aar We are also in the process to get it properly published so that it can be fetched again by Gradle

**Comment by theSoenke** [comment]
The problem has been addressed for now and fetching them via Jitpack should work again. Let me know in case you should still run into any issue. 

We are also considering multiple ideas to make fetching the library absolutely reliable in the future. I will keep you updated as soon as we have decided on that

**Comment by marlonbosse** [comment]
Thanks @theSoenke 👍 I will close this issue if thats fine for you.
