### ISSUE TITLE
Unable to download aar when using with another private jitpack library.

### ISSUE THREAD

**Issue by disparate** [phrase/phraseapp-android#2]
Hello, I've encountered following issue when using phraseapp OTA library for my project. 
Sometimes gradle is unable to download aar for the dependency (it returns 401 Unauthorized) if I also use another private jitpack library in the project.
When I use phraseapp lib alone it works perfect and always download the dependency during gradle sync.
I created an issue on jitpack's repo with detailed description (https://github.com/jitpack/jitpack.io/issues/3759) , but I'm not sure if the problem is on their side. Maybe you can take a look on it?

**Comment by theSoenke** [comment]
Hi, thanks for reporting this. It seems that Jitpack attemps to use the credentials for the private repo also for the public android-sdk repository which causes the failure. I've also left a comment in the issue

**Comment by disparate** [comment]
Thanks for the help @theSoenke
