### ISSUE TITLE
SDK crash if the resource is not found

### ISSUE THREAD

**Issue by mozarty** [phrase/phraseapp-android#5]
this line `this.setTextForView(view, resources.getString(attrs.getAttributeResourceValue(index, 0)))` in the TextViewTransformer
crashes with NoResourceFoundException when the resource isn't found because of the 0 int value

**Comment by theSoenke** [comment]
Hi @mozarty, thanks for reporting this. We are already working on a fix for it and it will most likely be released on Monday

**Comment by mozarty** [comment]
great !

**Comment by theSoenke** [comment]
Hi, just a quick update. The change is currently in QA and will be released shortly but probably not today anymore

**Comment by theSoenke** [comment]
Version 1.1.3 of the SDK has now been released. This should fix this issue. Please let me know if you should notice anything else unexpected

**Comment by mozarty** [comment]
Thanks alot
