### ISSUE TITLE
Strings containing HTML markup don't work when using OTA

### ISSUE THREAD

**Issue by bjoernQ** [phrase/phraseapp-android#7]
When using strings styled with HTML markup like `Welcome to <b>Android</b>!` work fine until using OTA. Then the displayed text shows the HTML tags instead of being styled the usual way

**Comment by theSoenke** [comment]
Hi @bjoernQ, thanks for reporting this. We were also able to reproduce it and are looking into it to fix this. I will keep you updated here as soon as I have some news

**Comment by theSoenke** [comment]
Version 1.1.4 was just released. This should resolve this. Thanks again for reporting this!

**Comment by bjoernQ** [comment]
Sounds great - we'll give it a try. Thanks for the fast fix
